---
output:
    github_document:
        html_preview: false
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = 'figures/',
  message = FALSE
)
```

# prelim

<!-- badges: start -->
<!-- badges: end -->

|   |   |   |
|---|---|---|
| Abstract | [PDF](docs/abstract.pdf) | [TeX](submission/abstract.tex) |
| Proposal | [PDF](docs/proposal.pdf) | [TeX](submission/proposal.tex) |
| Presentation | [gslides](https://docs.google.com/presentation/d/19kXLBr-lk_3Wva_raEzOGOYW2AH-GfA2ngcSSdOFJlY/edit?usp=sharing) | - |

## Dataset

```{r lib}
library(tidyverse)
```

```{r metadata}
metadata <- readxl::read_excel(here::here('data', 'GLNE07samples_baxter.xlsx'))
nrow(metadata)
metadata %>% 
    group_by(Diagnosis) %>% 
    summarize(n = n())

metadata %>%
    filter(Diagnosis != 'Pending', !is.na(Diagnosis)) %>% 
    mutate(Diagnosis = recode(Diagnosis,  
                              `High Risk Normal` = 'Normal')
           ) %>% 
    group_by(Diagnosis) %>% 
    summarize(n = n())
```

## Expected Outcomes

```{r functions}
set.seed(2019)
plot_auroc <- function(mldata) {
  mldata %>% ggplot(aes(model, auroc)) +
    geom_boxplot(color = "slategray3", width = 0.3, lwd = 1, fatten = 1) +
    geom_hline(yintercept = 0.5, 
               linetype = 'dashed',
               color = 'slategray3') +
    ylim(0.5, 1) +
    labs(y = 'AUROC', x = 'Model Features') +
    theme_classic(base_family = 'Chalkduster', 
                  base_size = 18) + 
    theme(axis.ticks.x = element_line(colour=NA),
          axis.line.x = element_blank(),
          axis.line.y = element_line(color = "slategray3"),
          text = element_text(color = 'darkslategray'),
          axis.text = element_text(color = 'darkslategray'))
}
```

```{r auroc_tax}

data.frame(OTUs = rnorm(100, .69, .04),
                  pathways = rnorm(100, .79, .04),
                  both = rnorm(100, .82, .04)) %>% 
    pivot_longer(everything(), names_to = "model", values_to = 'auroc') %>% 
    filter(auroc < 1) %>% 
    mutate(model = as_factor(model) %>% 
             recode(both = 'OTUs + pathways')) %>% 
  plot_auroc()
```

```{r auroc_metab}
data.frame(potential_pathways = rnorm(100, .75, .04),
                  active_pathways = rnorm(100, .83, .04)) %>% 
  pivot_longer(everything(), names_to = "model", values_to = 'auroc') %>%
  filter(auroc < 1) %>% 
  mutate(model = as_factor(model) %>% 
           recode(potential_pathways = 'potential pathways',
                  active_pathways = 'active pathways')) %>% 
  plot_auroc()
```

